- name: Configure System
  hosts: localhost
  tasks:
    - name: Configure Hostname
      become: true
      ansible.builtin.hostname:
        name: henrik-desktop
        use: systemd

    # Configure GNOME (desktop environment).
    # Tell dconf to synchronize the binary database with a plain text keyfile in ~/.config/dconf/user.txt.
    # This allows us to backup and restore our GNOME settings using deja-dup.
    # Ref: https://wiki.gnome.org/Projects/dconf/SystemAdministrators
    - name: Configure GNOME User Profile
      become: true
      ansible.builtin.copy:
        content: |
          service-db:keyfile/user
          user-db:user
          system-db:local
          system-db:site
          system-db:distro
        dest: /etc/dconf/profile/user
        mode: u=rw,g=r,o=r
