- name: Mount Disks
  hosts: localhost
  tasks:
    - name: Mount Data Disk
      become: true
      ansible.posix.mount:
        src: LABEL=Data
        path: /mnt/Data
        fstype: auto
        opts: nosuid,nodev,nofail,x-gvfs-show
        state: mounted

    - name: Mount Backup Disk
      become: true
      ansible.posix.mount:
        src: LABEL=Backup
        path: /mnt/Backup
        fstype: auto
        opts: nosuid,nodev,nofail,x-gvfs-show
        state: mounted

    - name: Create User Data Directory
      ansible.builtin.file:
        path: "/mnt/Data/{{ ansible_user_id }}"
        state: directory
        mode: u=rwx,g=,o=

    - name: Create User Backup Directory
      ansible.builtin.file:
        path: "/mnt/Backup/{{ ansible_user_id }}"
        state: directory
        mode: u=rwx,g=,o=
