- name: Configure GNOME Files (Nautilus)
  hosts: localhost
  tasks:
    - name: Sort Folders Before Files
      community.general.dconf:
        key: /org/gtk/gtk4/settings/file-chooser/sort-directories-first
        value: true
