# Creates a disabled user. An administrator must enable the user, for example by
# using the GNOME Settings app.
- name: Create User
  hosts: localhost
  become: true
  vars_prompt:
    - name: user_name
      prompt: User name
      private: false
  tasks:
    - name: Create User
      ansible.builtin.user:
        name: "{{ user_name }}"
        # Allow user to run Docker and Ollama commands without sudo.
        groups: docker,ollama
        append: true

    - name: Configure Déjà Dup Backups Folder
      community.general.dconf:
        key: "/org/gnome/deja-dup/drive/folder"
        value: "'{{ user_name }}'"
