- name: Create User Directories
  hosts: localhost
  vars_files:
    - vars/disk-vars.yml
  tasks:
    - name: Create User Data Directory
      ansible.builtin.file:
        name: "{{ user_data_path }}"
        state: directory
        mode: u=rwx,g=,o=

    - name: Change User Directories
      ansible.builtin.copy:
        content: |
          # This file is written by xdg-user-dirs-update
          # If you want to change or add directories, just edit the line you're
          # interested in. All local changes will be retained on the next run.
          # Format is XDG_xxx_DIR="$HOME/yyy", where yyy is a shell-escaped
          # homedir-relative path, or XDG_xxx_DIR="/yyy", where /yyy is an
          # absolute path. No other format is supported.
          #
          XDG_DESKTOP_DIR="{{ user_data_path }}/Desktop"
          XDG_DOWNLOAD_DIR="{{ user_data_path }}/Downloads"
          XDG_TEMPLATES_DIR="{{ user_data_path }}/Templates"
          XDG_DOCUMENTS_DIR="{{ user_data_path }}/Documents"
          XDG_MUSIC_DIR="{{ user_data_path }}/Music"
          XDG_PICTURES_DIR="{{ user_data_path }}/Pictures"
          XDG_VIDEOS_DIR="{{ user_data_path }}/Videos"
          XDG_PUBLICSHARE_DIR="{{ user_data_path }}/Public"
        dest: ~/.config/user-dirs.dirs
        mode: u=rw,g=,o=

    - name: Create Symbolic Link to Desktop Directory
      ansible.builtin.file:
        src: "{{ user_data_path }}/Desktop"
        dest: ~/Desktop
        state: link

    - name: Create Symbolic Link to Documents Directory
      ansible.builtin.file:
        src: "{{ user_data_path }}/Documents"
        dest: ~/Documents
        state: link

    - name: Create Symbolic Link to Downloads Directory
      ansible.builtin.file:
        src: "{{ user_data_path }}/Downloads"
        dest: ~/Downloads
        state: link

    - name: Create Symbolic Link to Music Directory
      ansible.builtin.file:
        src: "{{ user_data_path }}/Music"
        dest: ~/Music
        state: link

    - name: Create Symbolic Link to Pictures Directory
      ansible.builtin.file:
        src: "{{ user_data_path }}/Pictures"
        dest: ~/Pictures
        state: link

    - name: Create Symbolic Link to Public Directory
      ansible.builtin.file:
        src: "{{ user_data_path }}/Public"
        dest: ~/Public
        state: link

    - name: Create Symbolic Link to Templates Directory
      ansible.builtin.file:
        src: "{{ user_data_path }}/Templates"
        dest: ~/Templates
        state: link

    - name: Create Symbolic Link to Videos Directory
      ansible.builtin.file:
        src: "{{ user_data_path }}/Videos"
        dest: ~/Videos
        state: link

    - name: Create User Backup Directory
      ansible.builtin.file:
        name: "{{ user_backup_path }}"
        state: directory
        mode: u=rwx,g=,o=
