- name: Install Software
  hosts: localhost
  become: true
  tasks:
    # Required for installing proprietary software such as NVIDIA drivers and multimedia codecs.
    # Refs:
    # - https://docs.fedoraproject.org/en-US/quick-docs/rpmfusion-setup/
    # - https://rpmfusion.org/keys
    # - https://rpmfusion.org/Configuration
    - name: Import RPM Fusion Free GPG Key
      ansible.builtin.rpm_key:
        key: /usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-free-fedora-{{ ansible_distribution_major_version }}
        state: present
    - name: Import RPM Fusion Nonfree GPG Key
      ansible.builtin.rpm_key:
        key: /usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-nonfree-fedora-{{ ansible_distribution_major_version }}
        state: present
    - name: Install RPM Fusion Free Repository
      ansible.builtin.dnf:
        name: https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
        state: present
    - name: Install RPM Fusion Nonfree Repository
      ansible.builtin.dnf:
        name: https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
        state: present

    # Ref: https://rpmfusion.org/Howto/NVIDIA
    - name: Install NVIDIA Driver
      ansible.builtin.dnf:
        name: akmod-nvidia
        state: present
      notify:
        - Wait Until NVIDIA Kernel Module Has Been Built
    - name: Install CUDA Driver
      ansible.builtin.dnf:
        name: xorg-x11-drv-nvidia-cuda
        state: present

    # Required for encoding/decoding proprietary multimedia codecs.
    # Refs:
    # - https://docs.fedoraproject.org/en-US/quick-docs/installing-plugins-for-playing-movies-and-music/
    # - https://rpmfusion.org/Howto/Multimedia
    - name: Install FFmpeg
      ansible.builtin.dnf:
        name: ffmpeg
        state: present
        allowerasing: true # Replace ffmpeg-free with the RPM Fusion provided ffmpeg build.
    - name: Install Multimedia Libraries
      ansible.builtin.dnf:
        name: "@multimedia"
        state: present
    # Required for displaying thumbnails for HEIF and HEIC files.
    - name: Install libheif-tools
      ansible.builtin.dnf:
        name: libheif-tools
        state: present
    - name: Install Intel Media Driver for VAAPI
      ansible.builtin.dnf:
        name: intel-media-driver
        state: present
    - name: Install NVIDIA VAAPI Driver
      ansible.builtin.dnf:
        name: libva-nvidia-driver
        state: present

    # Required for enabling Google Chrome and Flathub repositories.
    # Refs:
    # - https://docs.fedoraproject.org/en-US/workstation-working-group/third-party-repos/
    # - https://flathub.org/setup/Fedora
    - name: Install Third-Party Repositores
      ansible.builtin.dnf:
        name: fedora-workstation-repositories
        state: present

    # Required for installing Google Chrome.
    # Ref: https://docs.fedoraproject.org/en-US/quick-docs/installing-chromium-or-google-chrome-browsers/
    - name: Enable Google Chrome Repository
      community.general.ini_file:
        path: /etc/yum.repos.d/google-chrome.repo
        section: google-chrome
        option: enabled
        value: 1
        create: false
        no_extra_spaces: true

    - name: Install Google Chrome
      ansible.builtin.dnf:
        name: google-chrome-stable
        state: present

    - name: Install Bitwarden
      community.general.flatpak:
        remote: flathub
        name: com.bitwarden.desktop
        state: present

    - name: Install Discord
      community.general.flatpak:
        remote: flathub
        name: com.discordapp.Discord
        state: present

    - name: Install Tweaks
      ansible.builtin.dnf:
        name: gnome-tweaks
        state: present

    - name: Install Extensions
      ansible.builtin.dnf:
        name: gnome-extensions-app
        state: present

    - name: Install Dconf Editor
      ansible.builtin.dnf:
        name: dconf-editor
        state: present

    - name: Install Backups
      ansible.builtin.dnf:
        name: deja-dup
        state: present

    - name: Install Solaar
      ansible.builtin.dnf:
        name: solaar
        state: present

  handlers:
    - name: Wait Until NVIDIA Kernel Module Has Been Built
      ansible.builtin.wait_for:
        timeout: 300 # 5 minutes
