- name: Install Audio Tools
  hosts: localhost
  become: true
  tasks:
    - name: Install FLAC
      ansible.builtin.dnf:
        name: flac
        state: present

    - name: Install Vorbis Tools
      ansible.builtin.dnf:
        name: vorbis-tools
        state: present

    - name: Install Opus Tools
      ansible.builtin.dnf:
        name: opus-tools
        state: present

    - name: Install GNU Parallel
      ansible.builtin.dnf:
        name: parallel
        state: present

    - name: Install MusicBrainz Picard
      ansible.builtin.dnf:
        name: picard
        state: present

    - name: Install rsgain
      ansible.builtin.dnf:
        name: rsgain
        state: present

    - name: Install Quod Libet
      ansible.builtin.dnf:
        name: quodlibet
        state: present

    - name: Install Playerctl
      ansible.builtin.dnf:
        name: playerctl
        state: present
