# Ref: https://docs.ollama.com/linux#manual-install
- name: Install Large Language Model (LLM) Tools
  hosts: localhost
  become: true
  tasks:
    - name: Download Ollama Package
      ansible.builtin.get_url:
        url: https://ollama.com/download/ollama-linux-amd64.tar.zst
        dest: /usr/local/src/ollama-linux-amd64.tar.zst
        mode: u=rw,g=r,o=r
      register: download_ollama_package

    - name: Extract Ollama Package
      ansible.builtin.unarchive:
        src: "{{ download_ollama_package.dest }}"
        dest: /usr/local
        remote_src: true

    - name: Download Ollama ROCm Package
      ansible.builtin.get_url:
        url: https://ollama.com/download/ollama-linux-amd64-rocm.tar.zst
        dest: /usr/local/src/ollama-linux-amd64-rocm.tar.zst
        mode: u=rw,g=r,o=r
      register: download_ollama_rocm_package

    - name: Extract Ollama ROCm Package
      ansible.builtin.unarchive:
        src: "{{ download_ollama_rocm_package.dest }}"
        dest: /usr/local
        remote_src: true

    - name: Create Ollama User
      ansible.builtin.user:
        name: ollama
        system: true
        shell: /bin/false
        create_home: true
        home: /usr/local/share/ollama

    - name: Create Ollama Service File
      ansible.builtin.copy:
        # The Radeon 780M is gfx1103 (also known as 11.0.3), however ROCm does
        # not currently support this target. The closest supported target is
        # gfx1102. To force the system to run on the Radeon 780M, set
        # environment variable HSA_OVERRIDE_GFX_VERSION=11.0.2 for the server.
        # Ref: https://docs.ollama.com/gpu#overrides-on-linux
        content: |
          [Unit]
          Description=Ollama Service
          After=network-online.target

          [Service]
          ExecStart=/usr/local/bin/ollama serve
          User=ollama
          Group=ollama
          Restart=always
          RestartSec=3
          Environment="PATH=$PATH"
          Environment="HSA_OVERRIDE_GFX_VERSION=11.0.2"

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/ollama.service
        mode: u=rw,g=r,o=r
      notify:
        - Enable and Restart Ollama Service

  handlers:
    - name: Enable and Restart Ollama Service
      ansible.builtin.systemd_service:
        daemon_reload: true
        name: ollama
        enabled: true
        state: restarted
