- name: Install Development Tools
  hosts: localhost
  become: true
  tasks:
    - name: Install tmux
      ansible.builtin.dnf:
        name: tmux
        state: present

    - name: Install Vim
      ansible.builtin.dnf:
        name: vim
        state: present

    - name: Install uv
      ansible.builtin.dnf:
        name: uv
        state: present
