- name: Install Audio Tools
  hosts: localhost
  become: true
  tasks:
    - name: Install GNU parallel
      ansible.builtin.dnf:
        name: parallel
        state: present

    - name: Install FLAC
      ansible.builtin.dnf:
        name: flac
        state: present

    - name: Install Vorbis-tools
      ansible.builtin.dnf:
        name: vorbis-tools
        state: present

    - name: Install Opus-tools
      ansible.builtin.dnf:
        name: opus-tools
        state: present

    - name: Install MusicBrainz Picard
      ansible.builtin.dnf:
        name: picard
        state: present

    # rsgain is the backend for the "ReplayGain 2.0" plugin in MusicBrainz Picard.
    # Requires plugin "ReplayGain 2.0" to be installed and enabled in MusicBrainz Picard.
    - name: Install rsgain
      ansible.builtin.dnf:
        name: rsgain
        state: present

    # Install Quod Libet instead.
    - name: Remove Rhythmbox
      ansible.builtin.dnf:
        name: rhythmbox
        state: absent

    - name: Install Quod Libet
      ansible.builtin.dnf:
        name: quodlibet
        state: present

    # Allow control of Quod Libet using multimedia keys.
    # Requires plugin "Linux Desktop Integration (MPRIS D-Bus)" to be enabled in Quod Libet.
    - name: Install Playerctl
      ansible.builtin.dnf:
        name: playerctl
        state: present
