- name: Install Large Language Model (LLM) Tools
  hosts: localhost
  become: true
  tasks:
    # Ref: https://docs.fedoraproject.org/en-US/quick-docs/ollama/
    - name: Install Ollama
      ansible.builtin.dnf:
        name: ollama
        state: present

    # Ref: # Ref: https://docs.ollama.com/linux#manual-install
    - name: Create Ollama User
      ansible.builtin.user:
        name: ollama
        system: true
        shell: /bin/false
        create_home: true
        home: /usr/share/ollama
    - name: Create Ollama Service File
      ansible.builtin.copy:
        content: |
          [Unit]
          Description=Ollama Service
          After=network-online.target

          [Service]
          ExecStart=/usr/bin/ollama serve
          User=ollama
          Group=ollama
          Restart=always
          RestartSec=3
          Environment="PATH=$PATH"

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/ollama.service
        mode: u=rw,g=r,o=r
      notify:
        - Enable and Restart Ollama Service

  handlers:
    - name: Enable and Restart Ollama Service
      ansible.builtin.systemd_service:
        daemon_reload: true
        name: ollama
        enabled: true
        state: restarted
