- name: Install Development Tools
  hosts: localhost
  become: true
  tasks:
    - name: Install tmux
      ansible.builtin.dnf:
        name: tmux
        state: present

    - name: Install Vim
      ansible.builtin.dnf:
        name: vim
        state: present

    - name: Install GitHub CLI
      ansible.builtin.dnf:
        name: gh
        state: present

    - name: Install uv
      ansible.builtin.dnf:
        name: uv
        state: present

    # Ref: https://docs.fedoraproject.org/en-US/quick-docs/installing-docker/
    - name: Install Docker
      ansible.builtin.dnf:
        name:
          - docker-cli
          - containerd
        state: present
    - name: Install Docker-Compose
      ansible.builtin.dnf:
        name: docker-compose
        state: present

    # Ref: https://docs.docker.com/engine/install/linux-postinstall/
    - name: Create Docker Group
      ansible.builtin.group:
        name: docker
        state: present
    - name: Enable Docker Service
      ansible.builtin.systemd_service:
        name: docker
        state: started
        enabled: true
    - name: Enable containerd Service
      ansible.builtin.systemd_service:
        name: containerd
        state: started
        enabled: true
    - name: Create Docker Configuration Directory
      ansible.builtin.file:
        name: /etc/docker
        state: directory
        owner: root
        group: root
        mode: u=rwx,g=rx,o=rx
    - name: Configure Docker Logging Driver
      ansible.builtin.copy:
        content: |
          {
            "log-driver": "local"
          }
        dest: /etc/docker/daemon.json
        mode: u=rw,g=r,o=r

    # Ref: https://docs.fedoraproject.org/en-US/quick-docs/using-kubernetes-versioned/
    - name: Install Kubernetes Client
      ansible.builtin.dnf:
        name: kubernetes-client
        state: present

    - name: Install Helm
      ansible.builtin.dnf:
        name: helm
        state: present

    - name: Install Azure CLI
      ansible.builtin.dnf:
        name: azure-cli
        state: present

    - name: Install OpenTofu
      ansible.builtin.dnf:
        name: opentofu
        state: present
