- name: Install Development Tools
  hosts: localhost
  become: true
  tasks:
    - name: Install tmux
      ansible.builtin.dnf:
        name: tmux
        state: present

    - name: Install Vim
      ansible.builtin.dnf:
        name: vim
        state: present

    - name: Install GitHub CLI
      ansible.builtin.dnf:
        name: gh
        state: present

    - name: Install uv
      ansible.builtin.dnf:
        name: uv
        state: present

    # Ref: https://docs.docker.com/engine/install/fedora/
    - name: Install Docker Engine Repository
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/fedora/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: u=rw,g=r,o=r
    - name: Install Docker Engine
      ansible.builtin.dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    # Ref: https://docs.docker.com/engine/install/linux-postinstall/#configure-docker-to-start-on-boot-with-systemd
    - name: Enable Docker Service
      ansible.builtin.systemd_service:
        name: docker
        enabled: true
    - name: Enable containerd Service
      ansible.builtin.systemd_service:
        name: containerd
        enabled: true

    # Ref: https://docs.fedoraproject.org/en-US/quick-docs/using-kubernetes-versioned/
    - name: Install kubectl
      ansible.builtin.dnf:
        name: kubernetes-client
        state: present

    - name: Install Helm
      ansible.builtin.dnf:
        name: helm
        state: present

    - name: Install Azure CLI
      ansible.builtin.dnf:
        name: azure-cli
        state: present

    # Ref: https://developer.hashicorp.com/terraform/install
    - name: Install HashiCorp Repository
      ansible.builtin.get_url:
        url: https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
        dest: /etc/yum.repos.d/hashicorp.repo
        mode: u=rw,g=r,o=r
    - name: Install Terraform
      ansible.builtin.dnf:
        name: terraform
        state: present
