- name: Mount Disks
  hosts: localhost
  vars_files:
    - vars/disk-vars.yml
  tasks:
    - name: Mount Data Disk
      become: true
      ansible.posix.mount:
        src: LABEL={{ data_disk_label }}
        path: "{{ data_disk_path }}"
        fstype: auto
        opts: nosuid,nodev,nofail,x-gvfs-show
        state: mounted

    - name: Mount Backup Disk
      become: true
      ansible.posix.mount:
        src: LABEL={{ backup_disk_label }}
        path: "{{ backup_disk_path }}"
        fstype: auto
        opts: nosuid,nodev,nofail,x-gvfs-show
        state: mounted
