- name: Mount Disks
  hosts: localhost
  vars_files:
    - vars/disk-vars.yml
  tasks:
    - name: Create Data Disk Mount Point
      become: true
      ansible.builtin.file:
        name: "{{ data_disk_path }}"
        state: directory
        mode: u=rwx,g=r-x,o=r-x

    - name: Mount Data Disk
      become: true
      ansible.posix.mount:
        src: LABEL={{ data_disk_label }}
        path: "{{ data_disk_path }}"
        fstype: auto
        opts: nosuid,nodev,nofail,x-gvfs-show
        state: mounted

    - name: Create Backup Disk Mount Point
      become: true
      ansible.builtin.file:
        name: "{{ backup_disk_path }}"
        state: directory
        mode: u=rwx,g=r-x,o=r-x

    - name: Mount Backup Disk
      become: true
      ansible.posix.mount:
        src: LABEL={{ backup_disk_label }}
        path: "{{ backup_disk_path }}"
        fstype: auto
        opts: nosuid,nodev,nofail,x-gvfs-show
        state: mounted
