- name: Setup Fedora Workstation
  hosts: workstation
  become: true
  roles:
    - gnome
    - third_party_software
    - development_tools
  tasks:
    - name: Install Visual Studio Code
      ansible.builtin.import_role:
        name: development_tools
        tasks_from: vscode.yaml
